### ISSUE TITLE
Add optional `timeout` to workflow steps

### ISSUE THREAD

**Issue by osterman** [cloudposse/atmos#1012]
### Describe the Feature

Steps in workflow can hang.

When the timeout is set, it will abort the step. If there is a retry configured and max retires is not reached. It will retry 

We should support human friendly time expressions.

Update the docs for workflows and custom commands with the new field

https://atmos.tools/core-concepts/workflows/

Implement a tests to verify the behavior.

```
workflows:
  super-slow-workflow:
    description: "Test timeouts"
    steps:
      - name: step1
        type: shell
        command: sleep 0.5
        
      - name: step2
        type: shell
        timeout: 1s
        command: sleep 2
```
        

        

### Expected Behavior

When the optional timeout parameter is set, and the commands execution time exceeds this timeout, the command is forcefully killed.

### Use Case

Sometimes commands can hang. Someone unaccustomed to running the workflow might not know what a reasonable amount of time is to wait. Adding a timeout, ensures that the command will abort after some known amount of time.

### Describe Ideal Solution

Support human readable timeouts.

`ms`, `s`, `m`, `h`, etc  We do this else where in atmos. Let's reuse the function.

Further more, if no modifier is specified, we should assume the timeout is in seconds.

```
workflows:
  super-slow-workflow:
    description: "Test timeouts"
    steps:
      - name: step1
        type: shell
        command: sleep 0.5
        timeout: 100ms
```

### Alternatives Considered

We could use another command like the `timeout` command on Linux and Mac, but the execution interface is not uniform. We want workflows to work easily across multiple platforms.
