### ISSUE TITLE
Add optional `working_directory` to Workflow Steps

### ISSUE THREAD

**Issue by osterman** [cloudposse/atmos#1013]
### Describe the Feature

Steps in a workflow may need to execute from different locations. 
Rather than put this common logic into the script portion of the command, we should support a `working_directory` setting.

Relative paths should be relative to the Atmos base directory. (aka `base-dir`). This keeps directory locations straightforward and determinisitc.

### Expected Behavior

Setting the `working_directory`, causes atmos to change directory into this location before executing the commands. If the directory does not exist, atmos exits with a clear error message.

### Use Case

- Run some raw terraform commands (e.g. `terraform import`) inside of a component directory.
- Run some commands in `/tmp` (e.g. to download files and unpack them)

### Describe Ideal Solution

```
workflows:
  test-1:
    description: "Test workflow"
    steps:
      - command: wget https://file-examples.com/wp-content/uploads/2017/02/zip_2MB.zip
        name: step1
        type: shell
        working_directory: /tmp
      - command: unzip zip_2MB.zip
        working_directory: /tmp
        type: shell
```

Alternatively, support a `working_directory` for the entire workflow.

```
workflows:
  test-1:
    description: "Test workflow"
    working_directory: /tmp
    steps:
      - command: wget https://file-examples.com/wp-content/uploads/2017/02/zip_2MB.zip
        name: step1
        type: shell

      - command: unzip zip_2MB.zip
        type: shell
```

With both options being able to be mixed and matched.

### Alternatives Considered

We could run `cd /some/path` as part of the command step. If the workflow command doesn't properly handle exit codes in the script, then it could proceed to run other commands causing damage.
