### ISSUE TITLE
Vendoring: "URI contains invalid characters"

### ISSUE THREAD

**Issue by mss** [cloudposse/atmos#1019]
### Describe the Bug

We are currently running v1.105.0 and want to update to the latest version. v1.158.0 is completely broken (we'll open a separate ticket for that) so we tried v1.157.0 (and a few versions before that).

And now our vendoring is broken:
```
~/.cache/tenv/Atmos/1.157.0/atmos vendor pull
Vendoring from 'vendor'
URI contains invalid characters
```

The problem is that we use an ampersand in our Git URLs for shallow clones, eg.:
```
    - component: mixins/context/v2.0
      version: v2.21.0
      source: git::https://git.example.com/scm/xxx/atmos-components.git//mixins/context?depth=1&ref={{.Version}}
      excluded_paths:
        - '**/README.md'
      tags:
        - mixins
        - mixins/context
      targets:
        - components/terraform/{{.Component}}
```

When I do a `sed -i -e 's/depth=1&//' vendor/*.yaml` vendoring works again.

### Expected Behavior

Vendoring is broken.

### Steps to Reproduce

Create a vendor config with an ampersand in the URL.

### Environment

- Version: 1.157.0

**Comment by mss** [comment]
I guess this might be the same issue as #832 which probably doesn't like the question mark in the URL which for some reason gets appended to the local directory?

**Comment by aknysh** [comment]
@mss  thanks for reporting the issues.
We'll investigate the `URI contains invalid characters` issue.
You are using this URL?

```
source: git::https://git.example.com/scm/xxx/atmos-components.git//mixins/context?depth=1&ref={{.Version}}
```

also, please provide more details about "v1.158.0 is completely broken"?

**Comment by osterman** [comment]
We'll fix this as part of:
- #984

**Comment by mss** [comment]
I did some poor man's bisecting using the script below and the issue was introduced in v1.130.0, ie. via #768.

Here is the test case (it can be simpler, the go templates aren't required):
```yaml
apiVersion: atmos/v1
kind: AtmosVendorConfig
metadata:
  name: gh-1019
  description: test
spec:
  sources:
    - component: atmos
      source: git::https://github.com/cloudposse/atmos.git?depth=1&ref={{.Version}}
      version: v1.129.0
      targets:
        - src/{{.Version}}
```

The script:
```bash
g=105
b=157
c=$b
while sleep 1; do
  v=1.$c.0
  echo $v
  sed -i -e "/version:/s/v1.*/v$v/" vendor.yaml
  mise exec atmos@$v -- atmos vendor pull
  if [[ -d src/v$v ]]; then
    g=$c
  else
    b=$c
  fi
  c=$(($g+($b-$g)/2))
done
```
