### ISSUE TITLE
Vendoring: "Path traversal" URI validation is broken and leaks URL

### ISSUE THREAD

**Issue by mss** [cloudposse/atmos#1027]
### Describe the Bug

While working on #1024 I ran into an odd issue with that "path traversal" check. It doesn't work as intended, instead some other check is failing. (We also saw some odd filesystem access when debugging #1019 which is probably the issue.)

This is generally not nice but as @osterman pointed out in the PR must the URLs not leaked via error messages since they may contain credentials.

### Expected Behavior

An error without the URL.

### Steps to Reproduce

Use this `vendor.yaml`:
```
apiVersion: atmos/v1
kind: AtmosVendorConfig
metadata:
  name: gh-1019
  description: test
spec:
  sources:
    - component: atmos-with-depth-and-error
      source: "git::https:///github.com/cloudposse/atmos.git?depth=1&ref={{.Version}}&bad=.."
      version: v1.129.0
      targets:
        - /tmp/atmos/{{.Version}}
```

### Screenshots

```
# build/atmos vendor pull
INFO Vendoring from 'vendor.yaml'
ERRO invalid source path 'git::https:///github.com/cloudposse/atmos.git?depth=1&ref=v1.129.0&bad=..': stat /home/me/Source/Misc/atmos/git::https:/github.com/cloudposse/atmos.git?depth=1&ref=v1.129.0&bad=..: no such file or directory
```

Ie. it tries to `stat` the path `$PWD/$uri`.

### Environment

- OS: Linux
- Version: 1.159.0

### Additional Context

* The error message is coming from here https://github.com/cloudposse/atmos/blob/v1.159.0/internal/exec/vendor_utils.go#L528
* The additional error handling in https://github.com/cloudposse/atmos/blob/v1.159.0/internal/exec/vendor_utils.go#L373 looks a bit odd as well.
