### ISSUE TITLE
Ability to List Component Variables

### ISSUE THREAD

**Issue by RoseSecurity** [cloudposse/atmos#1044]
### Describe the Feature

- It would be awesome to have the ability to list the variables of a component given the stack and component name, such as:

```sh
atmos list vars <COMPONENT> -s <STACK>
```

### Expected Behavior

- List the variables of a component:

```console
 √ . [infra] (HOST) workspace ⨠ atmos list vars eks/cluster -s dev-use1-plat
access_config:
    authentication_mode: API_AND_CONFIG_MAP
addons:
    aws-ebs-csi-driver:
        addon_version: v1.31.0-eksbuild.1
```

### Use Case

- While the `atmos describe component` command is useful, some of the output is not needed for day-to-day operations and workflows.
- Having an easy way to extract variables for a component is beneficial for quick troubleshooting.

### Describe Ideal Solution

Create a command that mimics this custom command functionality:

```yaml
  - name: list
    description: Execute 'list' commands
    # subcommands
    commands:
      - name: vars
        description: "List variables for an Atmos component in an Atmos Stack. Usage: atmos list vars <component> -s <stack>"
        arguments:
          - name: component
            description: Name of the component
        flags:
          - name: stack
            shorthand: s
            description: Name of the stack
            required: true
        component_config:
          component: "{{ .Arguments.component }}"
          stack: "{{ .Flags.stack }}"
        steps:
          - atmos describe component {{ .Arguments.component }} -s {{ .Flags.stack }} --query .vars
```
