### ISSUE TITLE
Vendor issue when using git ssh Urls

### ISSUE THREAD

**Issue by MrZablah** [cloudposse/atmos#1049]
### Describe the Bug

When using a Go-getter ssh git type url Atmos gives this error:
`ERRO parse "git@github.com:cloudposse/terraform-aws-tfstate-backend.git?ref=v1.5.0": first path segment in URL cannot contain colon`

### Expected Behavior

It should work and it used to work on older Atmos versions

### Steps to Reproduce

Use git ssh on the vendor.yaml file this:
```YAML
    - component: "terraform-null-label"
      source: "git::git@github.com:cloudposse/terraform-null-label.git?ref={{.Version}}"
      version: "0.25.0"
      targets:
        - "components/terraform/vendor/cloudposse/terraform-null-label"
      included_paths:
        - "**/*.tf"
        - "**/modules/**"
      excluded_paths:
        - "**/providers.tf"
      tags:
        - labels
```

then just do a normal `atmos vendor pull` cli cmd and this will give you and error.
