### ISSUE TITLE
Provider Configuration Not Inherited When Using Abstract Components and Context Provider

### ISSUE THREAD

**Issue by mirageAlchemy** [cloudposse/atmos#1143]
### Describe the Bug

When inheriting an abstract component (`demo`) with a `providers` configuration in the [Cloud Posse demo](https://github.com/cloudposse/atmos/tree/main/examples/demo-context)(the demo itself does not inherit but rather override), the `name: petset` value from the abstract component is not merged into the final `providers` configuration of the inheriting component. Other variables (e.g., `pet: "dog"`) are inherited, but the `name` field from the `context` provider is missing.  

### Expected Behavior

The `providers` section should deep-merge the `name: petset` from the abstract component and the `environment: dev` from the stack, resulting in:  
```yaml
providers:
  context:
    values:
      name: petset
      environment: dev
      support_email: dev-support@acme.com
```  

### Steps to Reproduce

1. **Define the abstract component** (`catalog/demo.yaml`):  
   ```yaml
   components:
     terraform:
       demo:
         metadata:
           type: abstract
           component: petset
         providers:
           context:
             values:
               name: petset
         vars:
           pet: "dog"
   ```  

2. **Define the stack** (`deploy/dev/demo.yaml`):  
   ```yaml
    # yaml-language-server: $schema=https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json

    import:
    - ../_defaults
    - catalog/demo
    - mixins/west-coast

    terraform:
      providers:
        context:
          values:
            environment: dev
            support_email: dev-support@acme.com

    components:
      terraform:
        demo-new: # this was `demo` in original demo
          metadata:
            inherits: # this was missing in the original demo
              - demo
            type: real
          vars:
            size: 3
   ```  
3. Run `atmos describe component demo -s deploy/dev`.  
4. Observe that the `name: petset` value is missing in the `providers.context.values` section.  

### Environment

OS: Linux/macOS (tested in Cloud Posse demo environment)
Atmos Version: 1.165.2+
Context Provider Configuration: same as in the demo

**Comment by thejrose1984** [comment]
### Not reproducible on current `main` — provider inheritance works as expected

I attempted to reproduce this on the latest `main` (commit `10dc5703e`) using the **exact** config from the report, in a copy of [`examples/demo-context`](https://github.com/cloudposse/atmos/tree/main/examples/demo-context). The `name: petset` value from the abstract component **is** deep-merged into the inheriting component's providers.

#### Repro setup

`stacks/catalog/demo.yaml` (unchanged abstract):
```yaml
components:
  terraform:
    demo:
      metadata:
        type: abstract
        component: petset
      providers:
        context:
          values:
            name: petset
      vars:
        pet: "dog"
```

`stacks/deploy/dev/demo.yaml` (the report's modified version — `demo-new` with `metadata.inherits`):
```yaml
import:
  - ../_defaults
  - catalog/demo
  - mixins/west-coast

terraform:
  providers:
    context:
      values:
        environment: dev
        support_email: dev-support@acme.com

components:
  terraform:
    demo-new:
      metadata:
        inherits:
          - demo
        type: real
      vars:
        size: 3
```

#### Result

> **Note on the stack name:** `demo-context`'s `atmos.yaml` derives stack names from a `name_template` (`{product}-{region}-{environment}`), so the stack is `acme-west-dev` rather than the manifest path `deploy/dev`. This only affects the `-s` value, not the merge behavior.

```console
$ atmos describe component demo-new -s acme-west-dev --query '.providers.context.values' --format yaml
component: demo-new
environment: dev
name: petset            # ✅ inherited from the abstract component
product: acme
region: west
stack: acme-west-dev
stack_file: deploy/dev/demo
support_email: dev-support@acme.com
```

This matches the **Expected Behavior** in the report — `name: petset` (from the abstract component), `environment: dev` and `support_email` (from the stack) are all deep-merged. Inheritance markers also resolve correctly: `metadata.component: petset`, `vars.pet: dog` (inherited), `vars.size: 3` (own).

#### Why it works

In [`internal/exec/stack_processor_merge.go`](https://github.com/cloudposse/atmos/blob/main/internal/exec/stack_processor_merge.go#L133-L154), the `providers` section is deep-merged across these layers (lowest → highest precedence):

1. stack-level `terraform.providers` (`TerraformProviders`)
2. **base/inherited component providers** (`BaseComponentProviders`) ← carries `name: petset`
3. the component's own `providers` (`ComponentProviders`)
4. `overrides.providers` (`ComponentOverridesProviders`)

`metadata.inherits` populates `BaseComponentProviders` from the abstract component, so its `providers` participate in the merge. The report was filed against `1.165.2` (2025-03); this appears to have been resolved since then.

#### Suggestion

Looks safe to **close as resolved**. @mirageAlchemy — could you confirm on a recent Atmos release? If you still see the value dropped, please share your `atmos.yaml` (specifically `name_pattern`/`name_template` and any `import`/overrides differences from the demo) so I can reproduce your exact setup.

<sub>Reproduced with a `test` build of `atmos` at `10dc5703e`.</sub>
