### ISSUE TITLE
Support configurable `atmos version` output

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#1169]
### Describe the Feature

The current `atmos version` returns this

```bash
✗ atmos version

 █████  ████████ ███    ███  ██████  ███████
██   ██    ██    ████  ████ ██    ██ ██
███████    ██    ██ ████ ██ ██    ██ ███████
██   ██    ██    ██  ██  ██ ██    ██      ██
██   ██    ██    ██      ██  ██████  ███████


👽 Atmos 1.162.1 on darwin/arm64
```

Ideally, we could return something like this

```bash
✗ atmos version | grep -i atmos | cut -d' ' -f3
1.162.1
```

### Expected Behavior

Shorter commandline output

### Use Case

- Less verbosity in local command line
- Less verbosity in pipeline output

### Describe Ideal Solution

A flag for the verbose option and the less verbose is the default

### Alternatives Considered

N/A

### Additional Context

N/A

**Comment by GabisCampana** [comment]
@aknysh

**Comment by osterman** [comment]
Open to an alternative output format. The current format will remain the default.

e.g. here's `kubectl`

```
❯ kubectl version --help  
Print the client and server version information for the current context.

Examples:
  # Print the client and server versions for the current context
  kubectl version

Options:
    --client=false:
	If true, shows client version only (no server required).

    -o, --output='':
	One of 'yaml' or 'json'.
```

```
❯ kubectl version -o yaml        
clientVersion:
  buildDate: "2023-09-13T09:35:49Z"
  compiler: gc
  gitCommit: 89a4ea3e1e4ddd7f7572286090359983e0387b2f
  gitTreeState: clean
  gitVersion: v1.28.2
  goVersion: go1.20.8
  major: "1"
  minor: "28"
  platform: darwin/arm64
kustomizeVersion: v5.0.4-0.20230601165947-6ce0bf390ce3
```

If you don't like color, set `NO_COLOR=1` and the atmos logo is not displayed.

```
❯ NO_COLOR=1 atmos version

👽 Atmos 1.165.1 on darwin/arm64

╭──────────────────────────────────────────────────────────────╮
│             Update available! 1.165.1 » 1.167.0              │
│ Atmos Releases: https://github.com/cloudposse/atmos/releases │
│          Install Atmos: https://atmos.tools/install          │
╰──────────────────────────────────────────────────────────────╯
```

And without version checks
```
❯ NO_COLOR=1 atmos version

👽 Atmos 1.165.1 on darwin/arm64
```
