### ISSUE TITLE
depends_on does not work

### ISSUE THREAD

**Issue by aabed** [cloudposse/atmos#1181]
### Describe the Bug

running `atmos apply  ecs` with depends_on section does not trigger dependency deploy

```
components:
  terraform:
    vpc:
      vars:
        cidr_block: "10.14.0.0/16" 
    ecs:
      settings:
        depends_on:
          1:
            component: "vpc"      
      vars: {}
```

vpc is not deployed when I run the command mentioned above

### Expected Behavior

vpc is deployed

### Steps to Reproduce

just add dependency and run the apply command

### Environment

Version: 1.87.1
Terraform version: 1.9.5
Linux/Arm
