### ISSUE TITLE
Atmos: implement `!include.template` YAML function (`!include` analog function to work with templates)

### ISSUE THREAD

**Issue by kinseii** [cloudposse/atmos#1182]
### Describe the Feature

Hi, in the latest version 1.169.0 I stopped having this construction in the tmpl file working:
```
        virtual_network:
          address_space: !include stacks/networks.yaml ".virtual_networks.{{ .common_name }}"
```

The way I pass this variable into the template is like this:
```
import:
  - path: templates/aks/v1.0.0/main.yaml.tmpl
    context:
      common_name: '{{ .settings.context.tenant }}-{{ .settings.context.env }}-{{ .settings.context.resource.name }}-{{ .settings.context.region }}-{{ .settings.context.resource.number }}'
```
Everything worked fine in version 1.168.0. Now it doesn't work because of !include function update.

Here is error:
```
invalid stack manifest 'templates/aks/v1.0.0/main.yaml.tmpl'
EvaluateYqExpression: failed to evaluate YQ expression '.virtual_networks.{{ .settings.context.tenant }}-{{ .settings.context.env }}-{{ .settings.context.resource.name }}-{{ .settings.context.region }}-{{ .settings.context.resource.number }}': bad expression, please check expression syntax
```

It is necessary to make an analog of the !include function to work with templates.

### Expected Behavior

Analog of the !include function to work with templates is exist.

### Use Case

Working with IaC.

### Describe Ideal Solution

.
