### ISSUE TITLE
`atmos describe component` not working as expected

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/atmos#119]
## Describe the Bug

When I run `atmos describe component s3 -s dev-internal.yaml` against my project, it fails with the following error: 

```
Found ENV var ATMOS_BASE_PATH=REDACTED

Could not find config for the component 's3' in the stack 'dev-internal.yaml'.
Check that all attributes in the stack name pattern '{environment}-{stage}' are defined in stack config files.
Are the component and stack names correct? Did you forget an import?
```

## Expected Behavior

I expect to see a YAML output of my final component configuration. 

## Steps to Reproduce
1. Go to a TF project
2. Run `atmos describe component <COMPONENT_NAME> -s <STACKPATH>

## Screenshots

N/A

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: `Debian Geodesic 0.149.2`
 - Version: Atmos v1.3.26

## Additional Context

Stack file: `stacks/dev-internal.yaml`
```yaml
import:
  - catalog/globals
  - catalog/dev-globals # environment is set here

settings:
  spacelift:
    labels:
      - deps:config/secrets/dev-internal-secrets.yml

vars:
  stage: internal

components:
  terraform:
    network:
      vars:
        vpc_cidr: 10.111.0.0/18

    s3:
      vars: {}

    cognito:
      vars: {}

	# ... 
```

Atmos config: `atmos.yaml`
```yaml
# See full configuration options @ https://github.com/cloudposse/atmos/blob/master/examples/complete/atmos.yaml

components:
  terraform:
    base_path: "./components/terraform"
stacks:
  base_path: "./stacks"
  name_pattern: "{environment}-{stage}"
```
