### ISSUE TITLE
Pin versions of vendor components

### ISSUE THREAD

**Issue by cfsb-jrose** [cloudposse/atmos#1194]
### Describe the Feature

When using components configured and downloaded using `atmos vendor pull`, it would be great to be able to set `required_providers` to pin provider versions.

### Expected Behavior

```
terraform:
  required_providers:
    aws:
      version: "5.0.0"
```

### Use Case

Implement required provider versions that would ensure the expected version is downloaded during `terraform init`

### Describe Ideal Solution

Update supporting code to permit the snippet shown in expected behavior.

### Alternatives Considered

Excluding `**/versions.tf` in vendor component configs and use:
```
terraform:
  providers:
    aws:
      version: "VERSION"
```
However, doing the above raises a deprecation warning. For example:
```
│ Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on providers_override.tf.json line 8, in provider.aws:
│    8:       "version": "5.79"
│ 
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now deprecated and will be removed in a future version of Terraform. To silence this warning, move the provider
│ version constraint into the required_providers block.
```

### Additional Context

https://sweetops.slack.com/archives/C031919U8A0/p1743694626702599

**Comment by cfsb-jrose** [comment]
Any traction on this? We recently discovered an issue with our ec2 component that breaks because of the latest aws provider version (6.0.0) and need a way to pin the version.

**Comment by osterman** [comment]
I can see how this would be helpful.

Since we already support generation of other sections of the `terraform { ... }` block like the `backend`, this would be easy to implement.

IMO, something like this would make sense, similar to provider overrides.

https://atmos.tools/core-concepts/components/terraform/providers/#provider-configuration-and-overrides-in-atmos-manifests

```
terraform:
  components:
    terraform:
      required_version: ">= 1.10.1"
      required_providers:
      aws:
        source: "hashicorp/aws"
        version: "~> 5.0"
```

Maps to this:

```hcl
terraform {

  required_version = ">= 1.10.1"

 required_providers {
  aws = {
   source = "hashicorp/aws"
   version = "~> 5.0"
  }
 }

 ...

 backend "s3" {
  bucket = "my-terraform-state"
  key  = "env/dev/terraform.tfstate"
  region = "us-west-2"
 }
```

And atmos would generate the following:

**File**: `terraform.override.tf.json`

```json
{
  "terraform": {
    "required_version": ">= 1.5.0",
    "required_providers": {
      "aws": {
        "source": "hashicorp/aws",
        "version": "~> 5.0"
      }
    }
  }
}
```
