### ISSUE TITLE
Bad characters when using the `!include` function

### ISSUE THREAD

**Issue by bl0way** [cloudposse/atmos#1205]
### Describe the Bug

Hello!

After playing around with the `!include` function It looks like it has a weird behaviour (to me) when some characters are present. 
If you use `!include mypath .my_var` with `my_var: '#<something>'` then it will be templated as `null` instead of `'#<something>'`. If the `#` characters is not present or is not in first position (after the single/double quote) then it works as expected.

I think it is a bug but as I am quite new on this tool, it could be also a wanted behaviour.

### Expected Behavior

The character `#` should not be templated as it is part of an escaped string when using the `!include` function. 

### Steps to Reproduce

Create a file `test.yml` with:
```
---
my_var: '#something`
```
Inside an other file, use the `!include` function to template the variable:
```
components:
  terraform:
    some_component:
      metadata:
        component: some_component
      vars:
        a_variable:
          templated_var: !include test.yml .my_var
```
The processed file `tfvars.json` will have `"templated_var": null`

### Environment

- OS: Debian12
- atmos 1.171.0
