### ISSUE TITLE
`atmos list vars` and `atmos list values` does not work on nested components

### ISSUE THREAD

**Issue by RoseSecurity** [cloudposse/atmos#1220]
### Describe the Bug

Running `atmos list vars` and `atmos list values` does not work on nested components such as `eks/cluster`.

Example:

```console
 √ . [infra] (HOST) workspace ⨠ atmos list vars eks/cluster --stack <stack>
ERRO component 'eks/cluster' does not exist
```

### Expected Behavior

Be able to list the vars and values of the component

### Steps to Reproduce

```sh
atmos list vars test/component -s <stack>
```

**Comment by osterman** [comment]
@RoseSecurity can you share the corresponding YAML of the component in the stack?

**Comment by RoseSecurity** [comment]
@osterman Would the catalog defaults be valuable or an `atmos describe component`?

**Comment by Cerebrovinny** [comment]
@RoseSecurity @osterman the output from describe can help identify the problem, or might fail for the same reason.
this would be a mix of filesystem path relative to the components base directory `(eks/cluster)` vs key `cluster` only, causing the problem, lets see the yaml before we discuss possible approaches to resolve this.

**Comment by RoseSecurity** [comment]
@osterman and @Cerebrovinny, here are the contents of the `defaults.yaml`:

```yaml
components:
  terraform:
    eks/cluster:
      settings:
        spacelift:
          workspace_enabled: true
          space_name_template: "{namespace}-plat"
      vars:
        enabled: true
        name: eks
        access_config:
          authentication_mode: API_AND_CONFIG_MAP
        availability_zones: [] # Use the VPC subnet AZs
        aws_ssm_agent_enabled: true
        ...
 ```

And the output of `atmos describe component`:

```console
# Component section
component: eks/cluster
component_info:
    component_path: /workspace/components/terraform/eks/cluster
    component_type: terraform
    terraform_config:
        path: /workspace/components/terraform/eks/cluster
        variables:
            access_config:
                name: access_config
                type: |-
                    object({
                        authentication_mode                         = optional(string, "API")
                        bootstrap_cluster_creator_admin_permissions = optional(bool, false)
                      })
                description: Access configuration for the EKS cluster
                default: {}
                required: false
                sensitive: false
```
