### ISSUE TITLE
atmos terraform generate planfile hangs

### ISSUE THREAD

**Issue by cfsb-jrose** [cloudposse/atmos#1223]
### Describe the Bug

While using `atmos terraform generate planfile` to produce plans in JSON format, I am observing that the process stalls and never produces a JSON file.

### Expected Behavior

`atmos terraform generate planfile vpc -s cfsb-it-platform-dev --format=json` should produce `/atmos/components/terraform/terraform-aws-vpc/cfsb-it-platform-dev-vpc.planfile.json`

### Steps to Reproduce

```
atmos terraform clean --force
atmos validate component vpc --stack cfsb-it-platform-dev
atmos terraform generate planfile vpc -s cfsb-it-platform-dev --format=json
```

### Screenshots

```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v5.96.0

Terraform has been successfully initialized!
```

### Environment

- OS: Alpine 3.21
- Atmos: v1.172.0
- Terraform: 1.11.4

**Comment by aknysh** [comment]
@cfsb-jrose  did you test it on just one component/stack?
does it work for other components?

**Comment by cfsb-jrose** [comment]
@aknysh it doesn't appear to work for any component. See attached debug logs.

[debug2.log](https://github.com/user-attachments/files/19961246/debug2.log)

**Comment by cfsb-jrose** [comment]
```
DEBU Writing the variables to file:
DEBU /atmos/components/terraform/terraform-aws-vpc/cfsb-it-platform-dev-vpc.terraform.tfvars.json
DEBU 
Validating the component 'vpc' using 'jsonschema' file 'vpc.json'
DEBU Validate 'vpc' component variables using JSON Schema
DEBU Writing the backend config to file. file=/atmos/components/terraform/terraform-aws-vpc/backend.tf.json
DEBU Writing the provider overrides to file. file=/atmos/components/terraform/terraform-aws-vpc/providers_override.tf.json
DEBU 
Using ENV vars:
DEBU ATMOS_CLI_CONFIG_PATH=/usr/local/etc/atmos
DEBU ATMOS_BASE_PATH=/atmos
DEBU TF_IN_AUTOMATION=true
DEBU TF_APPEND_USER_AGENT=Atmos/test (Cloud Posse; +https://atmos.tools)
DEBU Terraform environment file not found. No action needed. file=/atmos/components/terraform/terraform-aws-vpc/.terraform/environment
DEBU 
Executing command:
DEBU /usr/local/bin/terraform init -reconfigure
DEBU 
Command info:
DEBU Terraform binary: terraform
DEBU Terraform command: show
DEBU Arguments and flags: [-json /atmos/components/terraform/terraform-aws-vpc/new.plan]
DEBU Component: vpc
DEBU Terraform component: terraform-aws-vpc
DEBU Stack: cfsb-it-platform-dev
DEBU Working dir: /atmos/components/terraform/terraform-aws-vpc
DEBU 
Executing command:
DEBU /usr/local/bin/terraform workspace select cfsb-it-platform-dev-vpc
DEBU 
Executing command:
DEBU /usr/local/bin/terraform show -json /atmos/components/terraform/terraform-aws-vpc/new.plan
```
Just checked the submitted log and none of the DEBUG statements were captured, so adding here. It appears to get stuck when running `terraform show -json`

**Comment by aknysh** [comment]
did you se these ENV vars?

```
DEBU ATMOS_CLI_CONFIG_PATH=/usr/local/etc/atmos
DEBU ATMOS_BASE_PATH=/atmos
```

Not sure if it's causing the issue you are seeing.

Can you try to unset `ATMOS_BASE_PATH` (if possible) and test the command again?

**Comment by aknysh** [comment]
@cfsb-jrose  we have tests for `atmos terraform generate planfile` which are passing.
https://github.com/cloudposse/atmos/blob/main/internal/exec/terraform_generate_planfile_test.go

I'm not sure how to test your config. Maybe you can DM me your stack/component configurations and I'll test it?

**Comment by cfsb-jrose** [comment]
I am assuming `ATMOS_BASE_PATH` is set based on my config file since I am not setting that environment variable explicitly.

**Comment by cfsb-jrose** [comment]
Hello, I upgraded to [latest version](https://github.com/cloudposse/atmos/releases/tag/v1.182.0) of Atmos and still seeing issues. It appears to be stalling when running `terraform show`

```
DEBU Writing the variables file=/atmos/components/terraform/terraform-aws-security-group/wrappers/cfsb-ami-ue1-dev-terraform-aws-security-group-security-group.terraform.tfvars.json
DEBU Writing the backend config to file. file=/atmos/components/terraform/terraform-aws-security-group/wrappers/backend.tf.json
DEBU Writing the provider overrides to file. file=/atmos/components/terraform/terraform-aws-security-group/wrappers/providers_override.tf.json
DEBU Using ENV vars:
DEBU ATMOS_CLI_CONFIG_PATH=/usr/local/etc/atmos
DEBU ATMOS_BASE_PATH=/atmos
DEBU TF_IN_AUTOMATION=true
DEBU TF_APPEND_USER_AGENT=Atmos/test (Cloud Posse; +https://atmos.tools)
DEBU Terraform environment file not found. No action needed. file=/atmos/components/terraform/terraform-aws-security-group/wrappers/.terraform/environment
DEBU Executing command="/usr/local/bin/terraform init -reconfigure"
DEBU Terraform context executable=terraform command=show component=security-group stack=cfsb-ami-ue1-dev arguments and flags="[-json /atmos/components/terraform/terraform-aws-security-group/wrappers/new.plan]" terraform component=terraform-aws-security-group/wrappers inheritance="" working directory=/atmos/components/terraform/terraform-aws-security-group/wrappers
DEBU Executing command="/usr/local/bin/terraform workspace select cfsb-ami-ue1-dev-security-group"
DEBU Executing command="/usr/local/bin/terraform show -json /atmos/components/terraform/terraform-aws-security-group/wrappers/new.plan"
```

I am not sure how you're validating this functionality, but I need to know how if https://atmos.tools/cli/commands/terraform/generate-planfile is up to date because, without this functionality, I am unable to run security compliance.

**Comment by cfsb-jrose** [comment]
OK, so I have a lead...

If I mount [demo-stacks](https://github.com/cloudposse/atmos/tree/v1.182.0/examples/demo-stacks) inside my IAC Service Catalog image under `/atmos` and run `atmos terraform generate planfile myapp -s dev`, the command completes and generates the JSON plan file. This is a long shot, but here's my config file:

```yaml
base_path: "/atmos"

components:
  terraform:
    base_path: "components/terraform"
    apply_auto_approve: true
    deploy_run_init: true
    init_run_reconfigure: true
    auto_generate_backend_file: true

stacks:
  base_path: "stacks"
  included_paths:
    # Tell Atmos to search for the top-level stack manifests in the `orgs` folder and its sub-folders
    - "orgs/**/*"
  excluded_paths:
    # Tell Atmos that all `_defaults.yaml` files are not top-level stack manifests
    - "**/_defaults.yaml"
  # If you are using multiple organizations (namespaces), use the following `name_pattern`:
  name_pattern: "{namespace}-{tenant}-{environment}-{stage}"
  # If you are using a single organization (namespace), use the following `name_pattern`:
  # name_pattern: "{tenant}-{environment}-{stage}"

workflows:
  # Can also be set using 'ATMOS_WORKFLOWS_BASE_PATH' ENV var, or '--workflows-dir' command-line argument
  # Supports both absolute and relative paths
  base_path: "stacks/orgs/workflows"

logs:
  # Can also be set using 'ATMOS_LOGS_FILE' ENV var, or '--logs-file' command-line argument
  # File or standard file descriptor to write logs to
  # Logs can be written to any file or any standard file descriptor, including `/dev/stdout`, `/dev/stderr` and `/dev/null`
  file: "/dev/stderr"
  # Supported log levels: Trace, Debug, Info, Warning, Off
  # Can also be set using 'ATMOS_LOGS_LEVEL' ENV var, or '--logs-level' command-line argument
  level: Info

# Validation schemas (for validating atmos stacks and components)
schemas:
  # JSON Schema to validate Atmos manifests
  atmos:
    # Can also be set using 'ATMOS_SCHEMAS_ATMOS_MANIFEST' ENV var, or '--schemas-atmos-manifest' command-line arguments
    # Supports both absolute and relative paths (relative to the `base_path` setting in `atmos.yaml`)
    # manifest: "stacks/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json"
    # Also supports URLs
    manifest: "https://atmos.tools/schemas/atmos/atmos-manifest/1.0/atmos-manifest.json"
    # https://json-schema.org
  jsonschema:
    # Can also be set using `ATMOS_SCHEMAS_JSONSCHEMA_BASE_PATH` ENV var, or `--schemas-jsonschema-dir` command-line arguments
    # Supports both absolute and relative paths
    base_path: "stacks/schemas/jsonschema"
  opa:
    # Can also be set using `ATMOS_SCHEMAS_OPA_BASE_PATH` ENV var, or `--schemas-opa-dir` command-line arguments
    # Supports both absolute and relative paths
    base_path: "stacks/schemas/opa"

settings:
  terminal:
    max_width: 120        # Maximum width for terminal output
    pager: true           # Pager setting for all terminal output
    colors: true          # Enable colored output
    unicode: true         # Use Unicode characters in output
```
