### ISSUE TITLE
Opt in or opt out analytics for how atmos is used

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#123]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Would be nice to set the following in `atmos.yaml`

```yaml
analytics:
  # component names used
  components_enabled: true
  # if an error is found, hit an api endpoint that creates a ticket
  auto_crash_log_send_enabled: true
  # what commands are used the most often ?
  commands_enabled: true
  # etc
```

This may help mold atmos in the future to make it easier and extendable for everyone.
