### ISSUE TITLE
gomplate Fails When Used to Set vars in a Stack Import

### ISSUE THREAD

**Issue by aclarke822** [cloudposse/atmos#1241]
### Describe the Bug

```
vars:
  merged: !template '{{ toJson (datasource "vars_merged_final") }}'
```
Results in vars.merged resolving to the expected object, but
```
vars: !template '{{ toJson (datasource "vars_merged_final") }}'
```
fails. The structure of the object seems to be irrelevant. The error is the generic "Could not find the component ... in stack..."

Additionally, any property of the object can be successfully accessed:

```
vars:
  propA: '{{ (datasource "vars_merged_final").propA }}'
  propB: '{{ (datasource "vars_merged_final").propB }}'
  propC: '{{ (datasource "vars_merged_final").propC }}'
```

### Expected Behavior

vars.merged in scenario 1 and vars in scenario 2 should resolve to the same object in both scenarios.

### Steps to Reproduce

Use gomplate to set vars in a yaml file, import it into a stack and use atmos terraform plan/apply.

### Environment

Windows
Atmos 1.74.0
Terraform 1.11.3
