### ISSUE TITLE
a single ' causes atmos to error out when using !template tojson

### ISSUE THREAD

**Issue by minoseah629** [cloudposse/atmos#1250]
### Describe the Bug

have an atmos setup that uses !template toJson. 

within my json, I have a single ' inside a specific json field. 

![Image](https://github.com/user-attachments/assets/819430ae-8ee9-4912-8ed4-0391e2a7a1bf)

### Expected Behavior

atmos should be able to handle the json field to have ' with no issue. 

![Image](https://github.com/user-attachments/assets/e23a612d-334d-4b9e-966c-58bf82eb388d)

### Steps to Reproduce

in stack, use _defaults.yaml
```yaml
settings:
  templates:
    settings:
      gomplate:
        timeout: 5
        datasources:
          vars_defaults:
            url: "../../Variables/defaults.json"
```

in top level overrides.yaml, include 
```yaml
vars: 
  bedrock_agent_configs: !template '{{ toJson (datasource "vars_merged_final").bedrock_agent_configs }}'
```

in enviornment level (dev), override.yaml:
```yaml
settings:
  templates:
    settings:
      gomplate:
        timeout: 5
        datasources:
          vars_environment:
            url: ../../Variables/dev.json
          vars_merged_final:
            url: merge:vars_environment|vars_defaults
```

### Environment

OS: Window
version 26100.3915
module - n/a
terraform: 1.11.3
