### ISSUE TITLE
enable concurrent feature branch development

### ISSUE THREAD

**Issue by anthony-telljohann** [cloudposse/atmos#1253]
### Describe the Feature

My team would like to be able to work on multiple features concurrently.

### Expected Behavior

`team member one` should be able to  plan and apply changes to `feature a` without destroying resources created by `team member two` after they applied changes to `feature b`

### Use Case

I believe this use case would be valuable to any team that is large enough to have multiple team members working on new features concurrently.

### Describe Ideal Solution

The simplest way I think this could be solved is...

Given
- git branch is not `main` or `master`
When
- the user executes `atmos terraform plan` or `atmos terraform apply`
Then
- `atmos` should copy the existing workspace state to a new workspace with the same name with the git branch name appended, for example `tenant1-ue2-dev-feature-a`

### Alternatives Considered

We tried using the existing workspace feature but it doesn't work for us. We have a cloud provider that has 10,000+ resources that were created manually that we are trying to manage in atmos now. So anytime we try to use a new workspace, our `atmos plan` wants to create hundreds of new resources because we have already imported them and have removed the import statement.

**Comment by Benbentwo** [comment]
Hey @anthony-telljohann interesting idea. 

Theres a couple of problems we'd probably run into if we implemented this.

If `atmos` copied the existing workspace state to a new workspace based on the branch name you'd then be in a spot where you have 2 (or more) workspaces (state) managing the same resources. This then leads to a problem where one change on a feature branch would manipulate the same resources being tracked by `main` and other possible feature branches. This means that those other branches state is now stale and out of date with what is live in your cloud provider. This would lead to a lot overlapping resource management. 

This also introduces the problem of state merging. When a feature branch is complete, the state holds the added resources that the developer worked on; this state lives in a feature branch workspace. We then need to figure out a way to merge it with the main state. This would be highly dependent on the branching strategy that the team uses and varies from team to team.

We're open to hearing suggestions on the above, but before we go too deep into that solution, we want to consider what might be an easier, more `atmos` native solution, which is to utilize component instances.

It sounds like you have a component factory ( a component with a very large `for_each` or something in terraform that is generating a LOT of resources), typically we want to break this down into a couple of resources. It might seem unwieldy to try to create atmos stacks for 10,000 components but there's tooling to help.

I'd recommend trying to simplify the component to be a single (or couple of resources) then use a single stack instance or template. For example assuming your component is called `component-a`

Something like the following could work:

## Option 1: Template file and for looping in yaml
`stacks/catalog/component-a.template.yaml`
```
components:
  terraform:
    {{ range $identifier := .instances }}
    component-a/instance-{{ $identifier }}:
      metadata:
        component: component-a
#        inherits:
#          - component-a/defaults
      vars:
        attributes:
          - "{{ $identifier }}"
        foo:
          bar: baz
    {{ end }}
```
`some stack file`
```
import:
  - path: catalog/component-a.template.yaml
    context:
      instances:
        - abc
        - zyx
```

## Option 2: Template catalog with imports
`stacks/catalog/component-a.template.yaml`
```
components:
  terraform:
    component-a/instance-{{ .id }}:
      metadata:
        component: component-a
#        inherits:
#          - component-a/defaults
      vars:
        attributes:
          - "{{ .id }}"
        foo:
          bar: baz
```
`some stack file`
```
import:
  - path: "catalog/component-a.yaml"
    context:
      id: "{{ .id }}"
      instance: "{{ .instance }}"
```

The imports could also be setup to be dynamic which might help move state.

Docs for this type of import are [here](https://atmos.tools/core-concepts/stacks/imports/#go-templates-in-imports)
