### ISSUE TITLE
--verbose flag fails with `atmos describe affected` in v1.179.0 and v1.180.0, but works in v1.178.0

### ISSUE THREAD

**Issue by SaravShah** [cloudposse/atmos#1296]
### Describe the Bug

When using the [cloudposse/github-action-atmos-affected-stacks](https://github.com/cloudposse/github-action-atmos-affected-stacks) GitHub Action (v6.4.0) to determine affected stacks in CI, we’ve encountered a regression in Atmos versions v1.179.0 and v1.180.0: the --verbose flag passed to atmos describe affected now triggers a CLI error: `unknown flag --verbose for command atmos describe affected`

This issue does not occur in version v1.178.0, where the same flag works without error. The failure only began occurring after upgrading to later versions.

### Expected Behavior

The following invocation should work across all supported versions:
`atmos describe affected --include-settings=false --file affected-stacks.json --verbose=true --repo-path "$GITHUB_WORKSPACE/base-ref"`

At the very least, the flag should not error out, especially since --verbose is still listed in the command’s usage examples:

atmos describe affected --verbose=true
https://atmos.tools/cli/commands/describe/affected/ 

### Steps to Reproduce

This can be reproduced in a GitHub Actions job with the following configuration:
```
jobs:
  atmos-affected:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'no-plan') }}
    name: Determine Affected Stacks
    runs-on: ubuntu-latest
    environment: atmos
    steps:
      - id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v6.4.0
        with:
          atmos-version: 1.179.0  # or 1.180.0
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
          base-ref: ${{ github.event.pull_request.base.sha }}
          head-ref: ${{ github.event.pull_request.head.sha }}
          skip-atmos-functions: true
          process-functions: false
          process-templates: false
    outputs:
      stacks: ${{ steps.affected.outputs.matrix }}
      has-affected-stacks: ${{ steps.affected.outputs.has-affected-stacks }}

```
Setting atmos-version: 1.178.0 works correctly.

### Additional Context

✅ v1.178.0 — Works as expected

❌ v1.179.0 — Fails with unknown flag --verbose

❌ v1.180.0 — Same failure
