### ISSUE TITLE
Atmos terraform post-apply ssm hook support SecureString parameter creation

### ISSUE THREAD

**Issue by zack-is-cool** [cloudposse/atmos#1356]
### Describe the Feature

Expand SSM parameter creation options in atmos hooks to support SecureString parameters, KMS key selection, tags, and advanced parameter types.

### Expected Behavior

When using post-apply hooks to store values in SSM (as documented [here](https://atmos.tools/core-concepts/stacks/hooks/)), I should be able to:

Create SecureString parameters instead of just regular String parameters
Specify KMS keys for encryption (by alias or ID)
Add tags to the parameters
Create advanced parameters (higher size limits, increased quotas)
Configure parameter descriptions

### Use Case

I'm using atmos to store Terraform outputs in SSM parameters via post-apply hooks. Some outputs can contain sensitive data that should be encrypted. Being able to use SecureStrings with our own KMS keys would let us properly secure this data and meet compliance requirements.

### Describe Ideal Solution

extend the current hook configuration to support additional SSM parameter options - or do it at the store configuration level

```
hooks:
    store-outputs:
        command: store
        events:
            - after-terraform-apply
        name: dev/ssm
        parameter_type: SecureString
        kms_key: alias/my-key
        tags:
            Environment: prod
            Team: platform
        outputs:
            vpc_properties: .vpc_properties
```

Or potentially allow per-output configuration for mixed parameter types:

```
hooks:
    store-outputs:
        command: store
        events:
            - after-terraform-apply
        name: dev/ssm
        outputs:
            vpc_properties: 
                path: .vpc_properties
                parameter_type: String
            database_password:
                path: .database_password
                parameter_type: SecureString
                kms_key: alias/database-key
                tags:
                    Sensitive: "true"
```

### Alternatives Considered

Writing our own custom Terraform module to handle SSM parameter creation
