### ISSUE TITLE
Include derived components when filtering on a base component

### ISSUE THREAD

**Issue by Nuru** [cloudposse/atmos#142]
## Describe the Feature

When running a command like
```
atmos describe stacks --components=vpc 
```
I want to see stacks which refer to the `vpc` component by deriving from it. For example, if I have

```yaml
components:
  terraform:
    vpc-ipv6:
      metadata:
        component: vpc
      vars: {}
```

I want to see that in the output.

## Use Case

Similar to #141, I want to know what stacks are using a component, for example to update them when I make a breaking change to the component.
