### ISSUE TITLE
A way to prefix component names using an inheritable metadata

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#173]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

```yaml
# stacks/catalog/eks/defaults.yaml
components:
  terraform:
    eks/defaults:
      metadata:
        type: abstract
      settings:
        spacelift:
          workspace_enabled: true
      vars:
        enabled: true
```

```yaml
# stacks/catalog/eks/blue/defaults.yaml
import:
  - stacks/catalog/eks/defaults

components:
  terraform:
    eks/blue/defaults:
      metadata:
        type: abstract
        component_prefix: eks/blue
        inherits:
          - eks/defaults
```

```yaml
# stacks/catalog/eks/blue/defaults.yaml
import:
  - stacks/catalog/eks/blue/defaults

components:
  terraform:
    # resolve to eks/blue/cluster
    cluster:
      metadata:
        inherits:
          - eks/blue/defaults

    # resolve to eks/blue/reloader
    reloader:
      metadata:
        inherits:
          - eks/blue/defaults
```
