### ISSUE TITLE
`atmos vendor pull` + `component.yaml` mixins should support relative paths

### ISSUE THREAD

**Issue by Gowiem** [cloudposse/atmos#185]
## Describe the Feature

In a `component.yaml` file, we should be able to supply relative paths to `mixins` so that we can specify mixins as a local file instead of a remote file. 

## Use Case

The use-case is to use client specific mixin files. This enables mixin files to not need to be published to an open source repository and/or use token based GitHub URLs to fetch private repository files.

## Describe Ideal Solution

Something like the following would be great: 

```yaml
apiVersion: atmos/v1
kind: ComponentVendorConfig
metadata:
  name: s3-bucket-vendor-config
  description: Source and mixins config for vendoring of 's3-bucket' component
spec:
  source:
    # ...

  mixins:
    - uri: file:///../../mixins/providers.mixin.tf
      filename: providers.mixin.tf

```

## Alternatives Considered

N/A

## Additional Context

* See thread in Slack about using `file:///` and how it doesn't work for relative paths: https://sweetops.slack.com/archives/C031919U8A0/p1659032722469009
