### ISSUE TITLE
Allow a generic set of keys in integrations like atlantis

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#190]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Allow a generic set of keys in integrations like atlantis. This way we don't have to continuously update the interface whenever atlantis maintainers add/rename/delete configuration keys.

## Expected Behavior

Allow pass through generic keys from

```yaml
# atmos.yaml
integrations:
  atlantis:
    path: "atlantis.yaml"
    config_templates:
      default:
        version: 3
        key: value
```

```shell
atmos atlantis generate repo-config \
  --config-template default \
  --output-path=/dev/stdout
```

Should return

```yaml
# atlantis.yaml
version: 3
key: value
```

## references

- Created from https://github.com/cloudposse/atmos/pull/189#discussion_r964331455
