### ISSUE TITLE
Download an atmos.yaml base line configuration with a subcommand

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#202]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

It's difficult to get atmos working out of the box without prior knowledge of the atmos.yaml file. It would be nice to use an atmos subcommand to download an atmos.yaml file with some sane common defaults which could then be modified by the user.

## Describe Ideal Solution

```
# download default
# location could be https://github.com/cloudposse/atmos/v1.7.2/configs/default.yaml
atmos config init

# download default + atlantis integration
# location could be https://github.com/cloudposse/atmos/v1.7.2/configs/atlantis.yaml
atmos config init --flavor atlantis

# download default + terragrunt integration
# location could be https://github.com/cloudposse/atmos/v1.7.2/configs/terragrunt.yaml
atmos config init --flavor terragrunt
```

## Alternatives Considered

- add a configs dir to atmos repo
- Download using curl instead of an atmos subcommand

## Additional Context

N/A

**Comment by osterman** [comment]
I agree - there should be some baseline `atmos.yaml` either compiled into `atmos` or downloadable.

**Comment by osterman** [comment]
In this example, we download the `README.md.gotmpl` from the `github_org` specified in the `README.yaml`. Note the `name` parameter is overridden to `foobar`:

```
templates:
  readme:
    type: file
    aliases:
    - md
    source: [https://github.com/{{](https://github.com/%7B%7B) first (split "/" .github_repo) }} /.github/tree/main/README.md.gotmpl?raw=true
    target: README.md
    context:
     - import: README.yaml
     - parameters: 
         name: foobar
```
