### ISSUE TITLE
Atmos 1.10.1+ treats all paths as relative for `atmos vendor pull`

### ISSUE THREAD

**Issue by marsadle** [cloudposse/atmos#228]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Any version above 1.10.0 is treating GitHub URLs in the `component.yaml` file as local file references. Version 1.10.0 and below are working.

```
Pulling sources for the component 'ecr' from '/Users/markus/example-stack/components/terraform/ecr/github.com/cloudposse/terraform-aws-components.git/modules/ecr?ref=1.25.0' and writing to '/Users/markus/example-stack/components/terraform/ecr'

error downloading 'file:///Users/markus/example-stack/components/terraform/ecr/github.com/cloudposse/terraform-aws-components.git/modules/ecr?ref=1.25.0': source path error: stat /Users/markus/example-stack/components/terraform/account-map/github.com/cloudposse/terraform-aws-components.git/modules/ecr: no such file or directory
```

## Expected Behavior

It downloads the component's files.

## Steps to Reproduce
1. Install atmos 1.10.1 or higher
2. Use supplied `component.yaml`
3. Run `atmos vendor pull -c ecr`

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: macOS 12.6
 - Atmos Version >= 1.10.1

## Additional Context
`component.yaml`

```yaml
apiVersion: atmos/v1
kind: ComponentVendorConfig
metadata:
  name: ecr-vendor-config
  description: Source and mixins config for vendoring of 'ecr' component
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/ecr?ref={{.Version}}
    version: 1.25.0
    included_paths:
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.md"
    excluded_paths:
      - "**/context.tf"

  mixins:
    # https://github.com/hashicorp/go-getter/issues/98
    - uri: ../../mixins/context.tf
      filename: context.tf
    - uri: https://raw.githubusercontent.com/cloudposse/terraform-aws-components/{{.Version}}/modules/datadog-agent/introspection.mixin.tf
      version: 1.25.0
      filename: introspection.mixin.tf
```
