### ISSUE TITLE
Feature request: `atmos terraform deploy $component --all`

### ISSUE THREAD

**Issue by osterman** [cloudposse/atmos#292]
## Describe the Feature

Add a new `--all` flag which is mutually exclusive with the `--stack` flag (only one or the other can be specified).  Alternatively, the implementation could could be something more generalized like a `--match` flag which takes a regular expression. Then `--all` could just be an alias for `--match '.*'`.

Alternative names for `--all` might be `--all-stacks` or `--everywhere`.

## Expected Behavior

When `--all` is passed, every stack that has the `component` is defined, it is deployed. 

## Use Case

Make it faster and less error-prone to bring up coldstarts.

## Describe Ideal Solution

A clear and concise description of what you want to happen. If you don't know, that's okay.

## Alternatives Considered

Explain what alternative solutions or features you've considered.

Today, our workflows will have something like:

```yaml
deploy:
    description: team roles
    steps:
      - command: terraform deploy datadog-configuration -s mgmt-gbl-artifacts
      - command: terraform deploy datadog-configuration -s mgmt-gbl-audit
      - command: terraform deploy datadog-configuration -s mgmt-gbl-auto
      - command: terraform deploy datadog-configuration -s mgmt-gbl-corp
      - command: terraform deploy datadog-configuration -s mgmt-gbl-dns
      - command: terraform deploy datadog-configuration -s mgmt-gbl-network
      - command: terraform deploy datadog-configuration -s mgmt-gbl-security
      - command: terraform deploy datadog-configuration -s platform-gbl-dev
      - command: terraform deploy datadog-configuration -s platform-gbl-prod
      - command: terraform deploy datadog-configuration -s platform-gbl-sandbox
      - command: terraform deploy datadog-configuration -s platform-gbl-staging
```

This is error-prone, as stacks can be accidentally omitted.

This could be reduced to the following, which would be less error prone:

```
deploy:
    description: team roles
    steps:
      - command: terraform deploy datadog-configuration  --all
```

## Additional Context

Ideally, this could also support a `--parallel=5` option to run 5 processes in parallel.

**Comment by milldr** [comment]
How would we specify the region? Perhaps something like:

`--all-regions`
`--all --region=gbl`
`--all --region=use1`

```
deploy:
    description: datadog config in all accounts in gbl region
    steps:
      - command: terraform deploy datadog-configuration  --all --region=gbl
```
```
deploy:
    description: compliance  in all regions in mgmt-artifacts
    steps:
      - command: terraform deploy compliance mgmt-artifacts --all-regions
```
```
deploy:
    description: compliance in all regions in all accounts
    steps:
      - command: terraform deploy compliance --all --all-regions
```
