### ISSUE TITLE
Feature Request: Parallel Steps in Workflows

### ISSUE THREAD

**Issue by osterman** [cloudposse/atmos#302]
## Describe the Feature

During cold starts, there are frequently many steps that could be run in parallel, speeding up the provisioning.

## Expected Behavior

Support nested blocks of "steps" of type "parallel". When executed, all parallel steps of a step must complete before advancing to the next step.
```
workflows:
  test-1:
    description: "Test workflow"
    steps:
      - type: parallel
        steps:
        - command: echo Command 1
          name: step1
          type: shell
        - command: echo Command 2
          name: step2
          type: shell
```

If any step in the parallel execution fails, the next step in the workflow is not run. 

## Use Case

1. Cold starts. Bringing up EKS clusters, there are 10-15 services that could be deployed in parallel as they have no dependency on each other.

**Comment by jamengual** [comment]
should this have a configurable `count` for how many parallel process to
run?

**Comment by cfsb-jrose** [comment]
Not sure if this is relevant or not, but one thing that would be amazing if workflows could permit iteration of "like" commands. For example:
```
  ci-test:
    description: |
      The steps in this workflow are run when a pull request is created or updated.
      This workflow will run the full terraform lifecycle, including cleanup tasks.
    stack: cfsb-it-platform-dev4
    steps:
      - command: terraform clean --force
        components:
        - kms
        - vpc
        - iam
        - ec2
```
From the above, one could run `terraform clean --force` for a number of components in a given stack.
