### ISSUE TITLE
atmos generate backend is requiring the s3 workspace_key_prefix for remote backend

### ISSUE THREAD

**Issue by hypnotisttom** [cloudposse/atmos#332]
### Describe the Bug

I receive the message `Backend config for the 'mock-instance-1' component is missing 'workspace_key_prefix'` when running `atmos terraform generate backend mock-instance-1 -s self-ue2-test`.

This field should only be required for s3 backends, not remote backends.

### Expected Behavior

I would expect this field not to be required for backends that aren't s3.  As noted below, my workaround is to turn on autogenerate backend, which correctly does not require this field for my remote backend.

### Steps to Reproduce

_defaults.yaml

``` yaml
terraform:
  backend_type: remote
  backend:
    remote:
      hostname: app.terraform.io
      organization: <redacted>
      workspaces:
        prefix: app-
```

catalog entry:

``` yaml
components:
  terraform:
    mock-defaults:
      metadata:
        type: abstract
      backend:
        remote: {}
```

stack:

```yaml
import:
  - orgs/self/ue2/eng/_defaults
  - catalog/mock

vars: {}

components:
  terraform:
    mock:
      metadata:
        component: mock
        inherits:
          - mock-defaults
      vars: {}
```

Running: `atmos terraform generate backend mock-instance-1 -s self-ue2-test`

Produces: `Backend config for the 'mock-instance-1' component is missing 'workspace_key_prefix'`

But as I mentioned, autogenerating the backend works, the TF runs, indicating my backend config is correct.

### Environment

Mac
Installed atmos via brew - atmos version is 1.30.0
Terrform 1.3.7

### Additional Context

I am able to work around this by turning on autogenerate backend, which proceeds with running the terraform, indicating to me that my backend config in atmos is correct.  Apparently this is only an issue when attempting to generate the backend via the cli command specifically.

Please let me know if I'm doing anything wrong here.  Because this works with the autogenerating of the backend, I think my backend config is correct.

Thanks!
