### ISSUE TITLE
[Enhancement] Vendor pull from terraform private registries

### ISSUE THREAD

**Issue by Amos-85** [cloudposse/atmos#369]
### Describe the Feature

This feature is an enhancement for `Atmos Components` to be able to fetch terraform modules from private registries based on https.

### Expected Behavior

Ability to fetch terraform modules from private terraform registries

### Use Case

Many companies use private registries and repositories to:
-  Decoupled from vendor servers.
-  Fasten their pipeline builds.
-  Avoid breaking routine work when problems appear with vendor servers.
- Improve security.
- etc...

E.g:
- Docker
- Apt
- Rpm
- Npm
- Maven
- Helm
- Terraform
- etc...

### Describe Ideal Solution

**Option 1:**

After running `terraform login <some terraform private registry>`, credentials file being created under `~/.terraform.d/credentials.tfrc.json` .
If Atmos can look for this path on component initialization, it might solve the problem for any terraform registry use case as long as it work with native terraform registry authentication.

Reference: ==> [Terraform Credentials Storage](https://developer.hashicorp.com/terraform/cli/commands/login#credentials-storage)

**Option 2 (might be the preferred):**

Atmos will fetch the following environment variable in case of private registries `TF_TOKEN_cloudposse_jfrog_io=<terraform-private-registry-token>` , terraform translate the uri to `cloudposse.jfrog.io` .

Reference: ==> [Environment Variables Credentials](https://developer.hashicorp.com/terraform/cli/config/config-file#environment-variable-credentials)

**Comment by jamengual** [comment]
Hi @Amos-85 I'm using vendor pull right now and I'm trying to understand your usecase.

you are talking about the module instantiation source or the URL on the component.yaml that is read by atmos when you run `atmos vendor pull`?

**Comment by Amos-85** [comment]
Hi @jamengual ,
The use case is actually similar to [terragrunt tfr protocol ](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#terraform).

Currently I'm trying to run `atmos vendor pull -c aws/vpc` after setup `ComponenetVendorConfig` as below :

```
apiVersion: atmos/v1
kind: ComponentVendorConfig
metadata:
  name: vpc-vendor-config
  description: Source and mixins config for vendoring of 'vpc' component
spec:
  source:
    uri: "https://<company-domain>.jfrog.io/artifactory/<terraform-remote-repository>/terraform-aws-modules/terraform-aws-vpc/{{ .Version }}.zip"
    version: v4.0.1
    included_paths:
    - "**/*.tf"
    - "**/*.tfvars"
    - "**/*.md"
```
but it's failing to fetch the module with error `bad response code: 401` because of missing terraform private registry api token

It's fetching the module as expected if I'll use the uri with `username:password` as following:
```
uri: "https://<username>:<password>@<company-domain>.jfrog.io/artifactory/<terraform-remote-repository>/terraform-aws-modules/terraform-aws-vpc/{{ .Version }}.zip"
```
but it's not secure way to use credentials in configuration files.

**Comment by mss** [comment]
I think the simplest solution would be to just copy the (MIT licensed) Terragrunt `tfr` package from

* https://github.com/gruntwork-io/terragrunt/blob/main/terraform/getter.go
* https://github.com/gruntwork-io/terragrunt/blob/main/terraform/doc.go

and adapt the names of the used environment variables.

**Comment by joeccaulfield** [comment]
I am also trying to do something similar using private OCI images in GHCR and getting the same error.

```yaml
apiVersion: atmos/v1
kind: ComponentVendorConfig
metadata:
  name: acm
  description: Source and mixins config for vendoring of 'acm' component
spec:
  source:
    uri: oci://ghcr.io/<private-org>/terraform-aws-acm:{{.Version}}
    version: 1.5.0
    included_paths:
      - "**/*.tf"
      - "**/*.md"
    excluded_paths:
      - "**/context.tf"
  mixins:
    - uri: https://raw.githubusercontent.com/cloudposse/terraform-null-label/0.25.0/exports/context.tf
      filename: context.mixin.tf
```

![Image](https://github.com/user-attachments/assets/9f93c87d-c413-4d26-9628-e9696c92089e)
