### ISSUE TITLE
Command for Listing Stacks

### ISSUE THREAD

**Issue by RoseSecurity** [cloudposse/atmos#395]
### Describe the Feature

Would it be possible to incorporate a command for listing available stacks? I have been utilizing ```atmos describe stacks | grep -e '^\S' | sed s/://g``` to get a complete list of stacks, but if this could be incorporated as a command, it would be an awesome feature!

I am sure there is a more eloquent way of doing it, but even if the output of the ```atmos describe``` was passed to another function for parsing, this would be beneficial. 

```go
// describeStacksCmd describes configuration for stacks and components in the stacks
var describeStacksCmd = &cobra.Command{
	Use:                "stacks",
	Short:              "Execute 'describe stacks' command",
	Long:               `This command shows configuration for atmos stacks and components in the stacks: atmos describe stacks [options]`,
	FParseErrWhitelist: struct{ UnknownFlags bool }{UnknownFlags: false},
	Run: func(cmd *cobra.Command, args []string) {
		err := e.ExecuteDescribeStacksCmd(cmd, args)
		if err != nil {
			u.LogErrorAndExit(err)
		}
	},
}
```

### Expected Behavior

When the command is ran,  the terminal output would appear as the following:

```bash
(HOST) infra ⨠ atmos list stacks

dev-use1-admin
dev-usw2-admin
dev-use1-net
dev-usw2-net
```

### Use Case

It is difficult to know what stacks are available

### Describe Ideal Solution

Please see above

**Comment by aknysh** [comment]
@RoseSecurity  thank you for testing Atmos and opening this issue.

The command `atmos describe stacks` support many different parameters for filtering the stacks, see https://atmos.tools/cli/commands/describe/stacks

We agree that the filtering is not ideal, and we'll improve it to make it easier to filter for anything and output in any format. For example. output just the stack names, which is not supported now as you described above, but here is what supported and you can use it to get the stack names with a little help from `jq` or `yq`.

```shell
atmos describe stacks --sections none --component-types terraform
```

If you use `--sections none` parameter, you can get ALL the stack names with ALL the components in the stacks:

```yaml
tenant2-ue2-dev:
  components:
    terraform:
      infra/vpc: {}
      mixin/test-1: {}
      mixin/test-2: {}
      test/test-component: {}
      test/test-component-override: {}
      test/test-component-override-2: {}
      test/test-component-override-3: {}
      top-level-component1: {}
      vpc: {}
tenant2-ue2-prod:
  components:
    terraform:
      infra/vpc: {}
      infrastructure-tenant2: {}
      mixin/test-1: {}
      mixin/test-2: {}
      spacelift-defaults: {}
      test/test-component: {}
      test/test-component-override: {}
      test/test-component-override-2: {}
      test/test-component-override-3: {}
      top-level-component1: {}
      vpc: {}
tenant2-ue2-staging:
  components:
    terraform:
      infra/vpc: {}
      mixin/test-1: {}
      mixin/test-2: {}
      test/test-component: {}
      test/test-component-override: {}
      test/test-component-override-2: {}
      test/test-component-override-3: {}
      top-level-component1: {}
      vpc: {}
```

To see what stacks have a particular component, you can run:

```shell
atmos describe stacks --sections none --components top-level-component1
```

```yaml
tenant1-ue2-dev:
  components:
    terraform:
      top-level-component1: {}
tenant1-ue2-prod:
  components:
    terraform:
      top-level-component1: {}
tenant1-ue2-staging:
  components:
    terraform:
      top-level-component1: {}
tenant2-ue2-dev:
  components:
    terraform:
      top-level-component1: {}
tenant2-ue2-prod:
  components:
    terraform:
      top-level-component1: {}
tenant2-ue2-staging:
  components:
    terraform:
      top-level-component1: {}
```


To get a particular section for the component, e.g. `vars`, you can add the filter fro the sections, like so:

```shell
atmos describe stacks --sections vars --components top-level-component1
```

```yaml
tenant2-ue2-dev:
  components:
    terraform:
      top-level-component1:
        vars:
          enabled: true
          environment: ue2
          namespace: cp
          region: us-east-2
          service_1_name: top-level-service-1
          service_2_name: top-level-service-2
          stage: dev
          tenant: tenant2
tenant2-ue2-prod:
  components:
    terraform:
      top-level-component1:
        vars:
          enabled: true
          environment: ue2
          namespace: cp
          region: us-east-2
          service_1_name: top-level-service-1
          service_2_name: top-level-service-2
          stage: prod
          tenant: tenant2
tenant2-ue2-staging:
  components:
    terraform:
      top-level-component1:
        vars:
          enabled: true
          environment: ue2
          namespace: cp
          region: us-east-2
          service_1_name: top-level-service-1
          service_2_name: top-level-service-2
          stage: staging
          tenant: tenant2
```

So, although the filtering is not perfect and we'll be improving it, you can use the `--stack`,  `--components`, and `--sections` parameters to filter by stacks, components, and any sections of the component configs.

References:

* https://atmos.tools/cli/commands/describe/stacks
* https://atmos.tools/core-concepts/stacks/describing
