### ISSUE TITLE
Quickstart: region mixin

### ISSUE THREAD

**Issue by hans-d** [cloudposse/atmos#402]
### Describe the Bug

The quickstart provides an exampe for the vpc component with region mixin.
When generating the vars, the vars from the region mixin are not included.

### Expected Behavior

region vars included

### Steps to Reproduce

Follow the quickstart

### Screenshots

https://github.com/cloudposse/atmos/blob/9fe34c098385ae8f44f3223beed94b5fb3ed5210/website/docs/quick-start/create-atmos-stacks.md?plain=1#L207-L225

https://github.com/cloudposse/atmos/blob/9fe34c098385ae8f44f3223beed94b5fb3ed5210/website/docs/quick-start/create-atmos-stacks.md?plain=1#L314-L351

### Additional Context

When changing the "vpc" in the regions mixin to "vpc-1", the vars from the region mixin are included in the generated vars.

**Comment by thejrose1984** [comment]
### Not reproducible on current `main` — root cause was a component-name mismatch in the old quickstart, since fixed

I looked into this on current `main` (commit `6259051f`). The region-mixin vars **are** included now, and the underlying cause was a documentation/example inconsistency rather than an Atmos merge bug.

#### Root cause (the 2023 quickstart)

In the version linked in this issue, the region mixin defined component **`vpc`**:

```yaml
# stacks/mixins/region/us-east-2.yaml (old)
components:
  terraform:
    vpc:                       # <-- component "vpc"
      vars:
        availability_zones: [us-east-2a, us-east-2b, us-east-2c]
```

…but the parent stack deployed a *different* component, **`vpc-1`**, inheriting `vpc/defaults`:

```yaml
# stacks/orgs/acme/core/dev/us-east-2.yaml (old)
components:
  terraform:
    vpc-1:                     # <-- component "vpc-1", not "vpc"
      metadata:
        component: infra/vpc
        inherits: [vpc/defaults]
```

Atmos (correctly, by design) does not merge the vars of component `vpc` into a differently-named component `vpc-1`, so the mixin's `availability_zones` never reached the deployed component. This is exactly why your workaround — renaming the mixin's `vpc` to `vpc-1` — fixed it. So this was a **broken example in the docs**, not an engine bug.

#### Current state — fixed

The advanced quickstart docs and [`examples/quick-start-advanced`](https://github.com/cloudposse/atmos/tree/main/examples/quick-start-advanced) have since been restructured so the names are consistent. Region mixins now *import* a region-specific catalog manifest that targets the same `vpc` component:

```yaml
# stacks/mixins/region/us-east-2.yaml (current)
import:
  - catalog/vpc/ue2
vars:
  region: us-east-2
  environment: ue2
```

```yaml
# stacks/catalog/vpc/ue2.yaml (current)
import:
  - catalog/vpc/defaults
components:
  terraform:
    vpc:                       # same component name that gets deployed
      vars:
        availability_zones: [us-east-2a, us-east-2b, us-east-2c]
```

`vpc-1` no longer appears anywhere in the advanced quickstart doc.

#### Verification

```console
$ atmos describe component vpc -s plat-ue2-prod --query .vars.availability_zones --format yaml
- us-east-2a
- us-east-2b
- us-east-2c
# also: .vars.region = us-east-2, .vars.environment = ue2   ✅ region mixin vars included

$ atmos describe component vpc -s plat-uw2-prod --query .vars.availability_zones --format yaml
- us-west-2a
- us-west-2b
- us-west-2c
```

#### Suggestion

Looks safe to **close as resolved** — the quickstart example/docs that caused this were rewritten and the region mixin vars now merge correctly.

<sub>Verified with a `test` build of `atmos` at `6259051f` against `examples/quick-start-advanced`.</sub>
