### ISSUE TITLE
Retitle context's environment and stage for stacks

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#447]
### Describe the Feature

Currently it's this, which is confusing

```yaml
components:
  helmfile:
    helm_aws_profile_pattern: "{namespace}-{tenant}-gbl-{stage}-helm"
    cluster_name_pattern: "{namespace}-{tenant}-{environment}-{stage}-eks-cluster"

stacks:
  name_pattern: "{tenant}-{environment}-{stage}"
```

### Expected Behavior

Be able to alias these overloaded terms before a refactoring of the context.tf is completed

### Use Case

Trying to incorporate these inputs without confusing consumers

### Describe Ideal Solution

It would be nice to alias these somehow so we can do something like this

```yaml
aliases:
  short_region: "{environment}"
  account_name: "{stage}"

components:
  helmfile:
    helm_aws_profile_pattern: "{namespace}-{tenant}-gbl-{account_name}-helm"
    cluster_name_pattern: "{namespace}-{tenant}-{short_region}-{account_name}-eks-cluster"

stacks:
  name_pattern: "{tenant}-{short_region}-{account_name}"
```

### Alternatives Considered

No real workaround in atmos.yaml

One workaround we can do is to remove the tags by setting them to empty strings using which is helpful and doesn't confuse devs

```yaml
# orgs/acme/mixins/stage/dev.yaml
tags:
  Environment: ""
  Stage: ""
  AccountName: "dev"
```

but still need to keep the original names in atmos.yaml

### Additional Context

https://github.com/cloudposse/terraform-null-label/blob/main/variables.tf
https://github.com/cloudposse/terraform-null-label/blob/main/exports/context.tf
