### ISSUE TITLE
Support not specifying a component `spec.source`

### ISSUE THREAD

**Issue by kevcube** [cloudposse/atmos#488]
### Describe the Feature

I have components that are developed in the same repo as my stacks, I still want to use mixins with them. We would not need to use `source` or `atmos vendor pull`

A possible solution is an `atmos vendor mixin -c component`

### Expected Behavior

to be able to update mixins without `vendor pull`

### Use Case

To use mixins without vendor pull-ing any remote files

### Describe Ideal Solution

A possible solution is an `atmos vendor mixin -c component`

**Comment by nitrocode** [comment]
I'd like to also define the mixin directly in the `vendor.yaml` file

This way, whenever I pull a new vendor, it will copy in the mixin

```diff
apiVersion: atmos/v1
kind: AtmosVendorConfig
metadata:
  name: example-vendor-config
  description: Atmos vendoring manifest
spec:
  sources:
    - component: "vpc"
      source: "github.com/cloudposse-terraform-components/aws-vpc.git//src?ref={{.Version}}"
      version: "1.398.0"
      targets:
        - "components/terraform/vpc"
+     mixins:
+       - "mixins/terraform/providers.tf"
```

Sounds like there are 2 use cases

1. Re-add custom mixins when vendoring
2. Re-add custom mixins if mixins are updated

**Comment by j4zzcat** [comment]
I hit this with a central `vendor.yaml` manifest as well. The current behavior is surprising because `mixins` is accepted syntactically under an `AtmosVendorConfig` source, but `atmos vendor pull -c <component>` treats the source as generic vendoring and silently ignores the nested `mixins`.

Concrete use case:

```yaml
apiVersion: atmos/v1
kind: AtmosVendorConfig
metadata:
  name: cloudposse-byoc-components
spec:
  sources:
    - component: "cloudposse/aws-rds"
      source: github.com/cloudposse-terraform-components/aws-rds.git//src?ref={{ .Version }}
      version: v1.535.10
      targets:
        - "components/terraform/cloudposse/aws-rds"
      excluded_paths:
        - "providers.tf"
        - "remote-state.tf"
      mixins:
        - uri: github.com/org/infra.git//src/aws/components/terraform/cloudposse/aws-rds/src/providers.tf?ref={{ .Version }}
          version: main
          filename: "providers.mixin.tf"
        - uri: /workspace/src/aws/components/terraform/cloudposse/aws-rds/src/remote-state.tf
          filename: "remote-state.mixin.tf"
```

Expected:

- `atmos vendor pull -c cloudposse/aws-rds` vendors the source into the target.
- The excluded upstream files are skipped.
- The mixin files are copied afterward into the same target with the requested filenames.

Actual on Atmos `1.221.1`:

- The source is vendored and `excluded_paths` are honored.
- The nested `mixins` block is ignored.
- Debug output shows the source going through generic vendoring rather than component/mixin vendoring.

It would be useful for central `vendor.yaml` to support the same mixin overlay behavior as legacy component-local `ComponentVendorConfig`, especially for teams trying to keep vendoring configuration centralized while replacing provider/backend/remote-state files after each upstream pull.
