### ISSUE TITLE
Cannot reference terraform backend generate command in workflow

### ISSUE THREAD

**Issue by mathieusr** [cloudposse/atmos#49]
Hello,

When using `terraform backend generate` command in workflow it's not working due the code above. Any command with more than 2 arguments will not work in workflow

https://github.com/cloudposse/atmos/blob/f440764d05676bfee7da1235b701dbe073edb72c/atmos/modules/workflow/workflow.variant#L76-L79

Our workflow config file
```yaml
region-deploy-all:
    description: Deploy terraform project and helmfiles for a stack (provided as a command-line argument)
    steps:
      - job: terraform backend generate
      - job: terraform deploy dns-delegated
      - job: terraform deploy vpc
```

Perhaps need to add a specific option for commands who don't require any arguments

Thanks
