### ISSUE TITLE
Atmos generation of `backend.tf.json` is using deprecated `terraform.backend.s3.role_arn`

### ISSUE THREAD

**Issue by kevcube** [cloudposse/atmos#536]
### Describe the Bug

example backend.tf.json
```json
{
  "terraform": {
    "backend": {
      "s3": {
        "acl": "bucket-owner-full-control",
        "bucket": "bucket-name",
        "dynamodb_table": "table-name",
        "encrypt": true,
        "key": "terraform.tfstate",
        "region": "us-east-1",
        **"role_arn": "arn:aws:iam::123123123123:role/role-name",**
        "workspace_key_prefix": "workspace"
      }
    }
  }
}
```

warning:

```
╷
│ Warning: Deprecated Parameters
│ 
│ The following parameters have been deprecated. Replace them as follows:
│   * role_arn -> assume_role.role_arn
│ 
```

### Expected Behavior

backend.tf.json should be
```json
{
  "terraform": {
    "backend": {
      "s3": {
        ...
        "assume_role": {
          "role_arn": "arn:aws:iam::123123123123:role/role-name",
        }
        ...
      }
    }
  }
}
```

### Steps to Reproduce

error is raised in terraform 1.5.7

**Comment by aknysh** [comment]
@kevcube thanks.

This is what you control in the stack manifests, Atmos just uses the YAML config to generate the backend (it's not hardcoded in Atmos).

See:

- https://github.com/cloudposse/atmos/blob/master/examples/tests/stacks/orgs/cp/_defaults.yaml#L8
- https://atmos.tools/quick-start/configure-terraform-backend

So if you configure it like this:

```yaml
  backend:
    s3:
      encrypt: true
      bucket: "cp-ue2-root-tfstate"
      key: "terraform.tfstate"
      dynamodb_table: "cp-ue2-root-tfstate-lock"
      acl: "bucket-owner-full-control"
      region: "us-east-2"
      assume_role:
        role_arn: <role>
```

then Atmos will generate the backend file in the new format.
