### ISSUE TITLE
Feature request: `atmos vendor clean`

### ISSUE THREAD

**Issue by mss** [cloudposse/atmos#701]
### Describe the Feature

We are using the `vendor` feature a lot and especially while developing it is sometimes necessary to purge a vendored directory.

In our case it boils down to a `rm -rf components/terraform` and we could wrap it in a custom command. But it is a dangerous command to script due to the required `-f` flag (required for the `.git` directory within `.terraform/modules` and thus it would be nice if there was a "safer" command to give to our novice colleagues.

It would also be useful if flags like `--component` and the like were supported as well.

### Expected Behavior

An official, safe way to remove vendored stuff exists.

### Use Case

A safe way to remove vendored directories for novice users.

### Describe Ideal Solution

Calling `atmos vendor clean` will remove everything added by `atmos vendor pull`. If directories were vendored, they should be deleted recursively with everything included, including non-vendored files and directories.

**Comment by mss** [comment]
Potential problem to consider: What about mixins which are vendored (as directories, not single files) into non-vendored directories? Maybe #488 would be required to make that safe.

For example: I have something like this vendor configuration and `v2.0` and `v2.1` are actual vendored directories whereas `develop` is a symlink to the code I am working on. Ie. I'd expect `v2.0` and `v2.1` to be deleted due to their other vendor config but only the `context.tf` (which comes from the mixin) be removed from `develop`.

```
    - component: develop-context-mixin-v1.0
      source: components/terraform/mixins/context/v1.0
      targets:
        - components/terraform/foo/develop
        - components/terraform/foo/v2.0
        - components/terraform/foo/v2.1
```
