### ISSUE TITLE
Extend Component to include Catalog

### ISSUE THREAD

**Issue by milldr** [cloudposse/atmos#82]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

`component` only looks for components at the atmos components terraform base path, for example `/atmos_root/components/terraform`. It would be nice to be able to extend `component` to include components defined in the `catalog`. 

## Use Case

For example, say you have 1 component named `s3-bucket` and 2 implementations of that bucket named `s3-logs` and `s3-scripts`.  You could have a catalog with 3 files:
`catalog/s3-bucket/default.yaml`:
```
components:
  terraform:
    s3-bucket:
      backend:
        s3:
          workspace_key_prefix: s3-bucket
      vars:
           ...
```

`catalog/s3-bucket/s3-logs.yaml`:
```
import:
  - catalog/s3-bucket/default

components:
  terraform:
    s3-logs:
      component: s3-bucket
      vars:
        example-variable: foo
```

`catalog/s3-bucket/s3-scripts.yaml`:
```
import:
  - catalog/s3-bucket/default

components:
  terraform:
    s3-scripts:
      component: s3-bucket
      vars:
        example-variable: bar
```

Then in a stack, you could create these different components as such:
```
import:
- catalog/s3-bucket/default
- catalog/s3-bucket/s3-logs
- catalog/s3-bucket/s3-scripts

components:
  terraform:
    s3-example:
      component: s3-bucket
      vars:
        bucket_name: "example-default"
    s3-logs-example:
      component: s3-logs
      vars:
        bucket_name: "example-logs"
    s3-scripts-example:
      component: s3-scripts
      vars:
        bucket_name: "example-scripts"
```

For now, that would return this error:
`Component 's3-logs' does not exist in /atmos_root/components/terraform`
and
`Component 's3-scripts' does not exist in /atmos_root/components/terraform`
