### ISSUE TITLE
Atmos vendor pull leave files removed in new version

### ISSUE THREAD

**Issue by goruha** [cloudposse/atmos#821]
### Describe the Bug

Let's assume there are two versions of the component containing the following files.

## Version 1
* `main.tf`
* `locals.tf`

## Version 2
* `main.tf`

If you have pulled version 2 into a component that had already pulled version 1 the `locals.tf` would not be removed

### Expected Behavior

`atmos vendor pull --component {name}`  before pull should remove all files from component directory except `component.yaml` or `vendor.yaml`.

### Steps to Reproduce

Let's assume there are two versions of the component containing the following files.

1. Create component `aws-team-roles` in `components/terraform/aws-team-roles`
2. Create `components/terraform/aws-team-roles/component.yaml` file with the following content point to https://github.com/cloudposse/terraform-aws-components/tree/1.470.0/modules/aws-team-roles

```yaml
# 'aws-team-roles' component vendoring config

# 'component.yaml' in the component folder is processed by the 'atmos' commands
# 'atmos vendor pull -c aws-team-roles' or 'atmos vendor pull --component aws-team-roles'

apiVersion: atmos/v1
kind: ComponentVendorConfig
spec:
  source:
    uri: github.com/cloudposse/terraform-aws-components.git//modules/aws-team-roles?ref={{ .Version }}
    version: 1.470.0
    included_paths:
      - "**/**"
    excluded_paths: [ ]
```

3. Run `atmos vendor pull --component aws-team-roles`
4. Run `ls -l ` components/terraform/aws-team-roles` and check that files `policy-billing.tf` and `policy-support.tf` is there 
5. Update `components/terraform/aws-team-roles/component.yaml` replace `version: 1.470.0` with `version: 1.471.0`
point to https://github.com/cloudposse/terraform-aws-components/tree/1.471.0/modules/aws-team-roles
6. Run `atmos vendor pull --component aws-team-roles`

### Expected
1. Run `ls -l ` components/terraform/aws-team-roles` 
2. Ensure that files `policy-billing.tf` and `policy-support.tf` disappeared because they we removed in https://github.com/cloudposse/terraform-aws-components/tree/1.471.0/modules/aws-team-roles

### Exists
1. Run `ls -l ` components/terraform/aws-team-roles` 
2. The files `policy-billing.tf` and `policy-support.tf` still there
