### ISSUE TITLE
Trim whitespace of input variable values

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/atmos#91]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

If the trailing whitespace is inputted, atmos will include that into terraform

```
components:
  terraform:
    elasticache-redis:
      vars:
        redis_clusters:
          my-redis:
            parameters:
              - name: activedefrag
                # there is a bunch of whitespace after "no"
                value: no        
```

It would be nice if all whitespace from input values could be trimmed when creating the tfvars file
