### ISSUE TITLE
Unmarshalling of atmos.yaml not working as expected

### ISSUE THREAD

**Issue by dre2004** [cloudposse/atmos#93]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
I have been trying to get the stack.name_pattern to read from the atmos.yaml file to no avail. The pattern only works if I use an environment variable.

## Expected Behavior
I expect that the value I set in atmos.yaml under the components.stacks.name_pattern key to be used to find the stack

## Steps to Reproduce
1. Set stacks.name_pattern to anything
2. Run `atmos terraform plan <component> -s <stack>` I get the following message `must be provided in 'stacks.name_pattern' config or 'ATMOS_STACKS_NAME_PATTERN' ENV variable`
3. Set environment variable  `export ATMOS_STACKS_NAME_PATTERN="{tenant}-{environment}-{stage}"`. This seem to work.

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: Linux Mint 20.2 & Docker (debian bullseye)

## Additional context 
atmos.yaml
``` yaml
components:
  terraform:
    base_path: "./components/terraform"
    apply_auto_approve: false
    deploy_run_init: true
    auto_generate_backend_file: false
  helmfile:
    base_path: "./components/helmfile"
    kubeconfig_path: "/dev/shm"
    helm_aws_profile_pattern: "{namespace}-{tenant}-gbl-{stage}-helm"
    cluster_name_pattern: "{namespace}-{tenant}-{environment}-{stage}-eks-cluster"

  stacks:
    base_path: "./stacks"
    included_paths:
      - "**/*"
    excluded_paths:
      - "globals/**/*"
      - "catalog/**/*"
      - "**/*globals*"
    name_pattern: "{tenant}-{environment}-{stage}"

  logs:
    verbose: true
    colors: true

```
