### ISSUE TITLE
`vendor pull` does not print error message when an error occurs while installing the last component

### ISSUE THREAD

**Issue by ohaibbq** [cloudposse/atmos#935]
### Describe the Bug

`vendor pull` does not print error message when an error occurs while installing the last component

### Expected Behavior

Some information is shown to the user.

### Steps to Reproduce

1. Create the following `vendor.yaml` that specifies a fake OCI registry
```yaml
apiVersion: atmos/v1
kind: AtmosVendorConfig
metadata:
  name: Vendor configuration for recidiviz-dashboards
spec:
  sources:
    - component: "fake-component"
      source: "oci://us-central1-docker.pkg.dev/fake123/fake456/fake789:{{.Version}}"
      targets:
        - components/terraform/vendor/fake-component
      version: latest
```
2. Run `atmos vendor pull` with an interactive terminal
3. Observe the following output:
```
x fake-component (latest)
                                                         
  Vendored 0 components. Failed to vendor 1 components.  
```

Expected output:
```
x fake-component (latest) Failed to vendor fake-component: error : failed to process OCI image: cannot get image 'us-central1-docker.pkg.dev/fake123/fake456/fake789:latest'. Error: GET https://us-central1-docker.pkg.dev/v2/token?scope=repository%3Afake123%2Ffake456%2Ffake789%3Apull&service=: DENIED: Artifact Registry API has not been used in project 607861636108 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=607861636108 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
                                                         
  Vendored 0 components. Failed to vendor 1 components.  
```

### Additional Context

Additionally, I'm not sure why logs are hidden from the user in interactive mode.
There should probably be a way to enable logging, especially to files, when running interactively.
