### ISSUE TITLE
`vendor pull` fails for components under `cloudposse-terraform-components` org

### ISSUE THREAD

**Issue by ricky26j** [cloudposse/atmos#937]
### Describe the Bug

Running `atmos vendor pull` fails for components under the new `cloudposse-terraform-components` GitHub Organization.

### Expected Behavior

Running `atmos vendor pull` when the uri points to the `cloudposse-terraform-components` organization should successfully vendor the component, just as it does for components in the `cloudposse/terraform-aws-components` repo.

### Steps to Reproduce

First, I tried vendoring the component from the new GitHub Organization, with the following `component.yaml`

```

# 'dynamodb' component vendoring config

apiVersion: atmos/v1
kind: ComponentVendorConfig
metadata:
  name: dynamodb-vendor-config
  description: Source and mixins config for vendoring of 'dynamodb' component
spec:
  source:
    uri: github.com/cloudposse-terraform-components/aws-dynamodb.git//src?ref={{.Version}}
    version: 1.535.0
    included_paths:
      # include '.tf', '.tfvars' and '.md' files from the root folder
      - "**/*.tf"
      - "**/*.tfvars"
      - "**/*.md"
      - "**/modules/**"
      # include '.tf', '.tfvars' and '.md' files from the 'modules' folder and all sub-folders
      - "**/modules/**/*.tf"
      - "**/modules/**/*.tfvars"
      - "**/modules/**/*.md"
    excluded_paths: []

  mixins: []

```

This was the output of the command:

```
$ atmos vendor pull --component gitops/dynamodb 
x gitops/dynamodb (1.535.0)
                                                         
  Vendored 0 components. Failed to vendor 1 components. 
```

I then ran `atmos vendor pull` with `component.yaml` exactly the same, except replacing the `uri` with ` github.com/cloudposse/terraform-aws-components.git//modules/dynamodb?ref={{.Version}}`.

```
$ atmos vendor pull --component gitops/dynamodb 
✓ gitops/dynamodb (1.535.0)
                          
  Vendored 1 components. 
```

### Environment

- atmos 1.146.1
- Mac OS Sequoia 15.0 with M4 chip

### Additional Context

Let me know if you need more info, or if this belongs in a different repo, like the component's repo.
